# Site settings
title: ScribbleScape
# email: ?
# url: https://github.com/jeromelachaud/freelancer-theme
description: "Game studio making beautiful games."
keywords: "Tiny, original, video games, interactive"
skills: "Making beautiful games"
# meta_author: 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a1f29ff #BDE4A8 #79B4A9 #9CC69B #A1B0AB #18bc9c #80B3FF
  primary-rgb: "202, 176, 39" #"128,179,255"
  secondary: ab9522 #676F54 #0D5C63 #C3DAC3 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  #primary: 9CC69B #BDE4A8 #79B4A9 #9CC69B #A1B0AB #18bc9c #80B3FF
  #primary-rgb: "24,288,156" #"128,179,255"
  #secondary: 647341 #676F54 #0D5C63 #C3DAC3 #2c3e50 #FD6E8A
  #secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: ScribbleScape Ltd 2020 -
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/scribblescape
  - title: tikok
    url: http://tiktok.com/@scribble_scape
  #- title: facebook
    # url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 71-75 Shelton Street
  - line: London, WC2H 9JQ 

# Credits content
credits: 'Thanks Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
